# https://github.com/actions/setup-dotnet for auth, last section

name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.403"

      - name: run build script
        run: |
          chmod +x ./build.sh
          ./build.sh -c Release -t pack
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: publish nuget package
        run: |
          dotnet nuget push .nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
